#
# BASE CONFIGURATION
#

# `base_url` should only be changed if your site isn't hosted at the root of a domain.
# `domain` is used to generate absolute URLs. (required to generate a valid feed)
#
#   Example:
#       http://my-site.com/
#           base_url: /
#           domain: my-site.com
#       http://my-site.com/my-blog/
#           base_url: /my-blog/
#           domain: my-site.com
base_url: /
domain: derwolfe.net


#
# METADATA
#

# Used in header meta tags and the site feed. (required to generate a valid feed)
author: Chris Wolfe
# A description of your site to be used in header meta tags.
description:
# Used in the site feed.
email: chris@derwolfe.net
# Your site's subtitle.
#subtitle: subtitle
# Your site's title. (required to generate a valid feed)
title: Chris Wolfe
date_format: '%B %d, %Y'
pygmentize: True
